export MYSQL_HOST=localhost
export MYSQL_PORT=3306
export MYSQL_DATABASE=coursera
export MYSQL_USERNAME=root
export MYSQL_PASSWORD=

export POSTGRES_HOST=localhost
export POSTGRES_PORT=5432
export POSTGRES_DATABASE=postgres
export POSTGRES_USERNAME=postgres
export POSTGRES_PASSWORD=

export SNOWFLAKE_TABLE=digible_schema.snowflake_table
export SQLSERVER_TABLE=digible_schema.sqlserver_table
export MAPPING_TABLE=digible_schema.mapping_table
